config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :likes
      get :likeds
    end
    #collection do
     # get :search
    #end
  end
  
  resources :microposts, only: [:create, :destroy, :show] do
    member do
      post :retweet
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :relationshiplikes, only: [:create, :destroy]
  resources :replies
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
  mount_uploader :picture, PictureUploader
  #validate  :picture_size
  has_many :relationshiplikes, dependent: :destroy
  has_many :likes, through: :relationshiplikes, source: :micropost, dependent: :destroy
  
  has_many :replies
  
  # アップロードされた画像のサイズをバリデーションする
   # def picture_size
    #  if picture.size > 5.megabytes
     #   errors.add(:picture, "should be less than 5MB")
      #end
    #end
  
  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def show
    @micropost = Micropost.find(params[:id])
    @reply = Reply.new(micropost_id: @micropost.id)
    @replies = @micropost.replies
  end

  
  def create
    #binding.pry
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = 'メッセージを投稿しました。'
      redirect_to root_url
    else
      @microposts = current_user.microposts.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'メッセージの投稿に失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  def retweet
    p "**********retweet_start**************"
    original_micropost = Micropost.find(params[:id])
    @micropost = current_user.microposts.build(original_id: original_micropost.id)
    @micropost.content = original_micropost.content
    @micropost.picture = original_micropost.picture
    
    if @micropost.save
      flash[:success] = 'リツイートしました。'
      redirect_to current_user
    else
      flash.now[:danger] = 'リツイートに失敗しました。'
      redirect_back(fallback_location: root_url)
    end
    p "**********retweet_end****************"
  end
  
  private
  
  def micropost_params
    params.require(:micropost).permit(:content, :picture)
  end
  
  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    unless @micropost
    redirect_to root_url
    end
  end
end

app/views/microposts/_microposts.html.erb
<ul class="media-list">
  <% microposts.each do |micropost| %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(micropost.user, { size: 50 }) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= link_to micropost.user.name, user_path(micropost.user) %> <span class="text-muted">posted at <%= micropost.created_at %></span>
        </div>
        <div>
          <% if micropost.original_id.present? %>
            <p></p><%= Micropost.find(micropost.original_id).user.name %>さんのリツイート</P>
          <% end %>
          <p><%= micropost.content %></p>
          <%= image_tag (micropost.picture.url) if micropost.picture? %>
        </div>
        <div>
        <% if current_user == micropost.user %>
           <%= link_to "Delete", micropost, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
        <% end %>
        <%= link_to "詳細", micropost %>
        <%= render 'relationshiplikes/like_button', user: @user, micropost: micropost %>
        <%= link_to "リツイート", retweet_micropost_path(micropost), method: :post %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate microposts %>
</ul>

app/views/microposts/show.html.erb
<h1><%= @micropost.content %></h1>

<%= form_for(@reply) do |f| %>
  <%= f.hidden_field :micropost_id %> 
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

<ul>
  <% @replies.each do |reply| %>
    <li><%= reply.content %></li>
  <% end %>
</ul>